# SPDX-PackageName: robotfindskitten
# SPDX-PackageDownloadLocation: https://codeberg.org/robotfindskitten/robotfindskitten
# SPDX-FileCopyrightText: © 1997 Leonard Richardson and contributors
# SPDX-License-Identifier: GPL-2.0-or-later

info_TEXINFOS = robotfindskitten.texi
man_MANS = robotfindskitten.6
EXTRA_DIST = $(man_MANS)
