.TH ROBOTFINDSKITTEN 6 "October 11, 2005"
.\"
.SH NAME
robotfindskitten - help robot find kitten
.\"
.SH SYNOPSIS
.B robotfindskitten
.RI [ number ]
.\"
.SH DESCRIPTION
In this game, you are robot
.RB ( # ).
Your job is to find kitten. This task is complicated by the existence of
various things which are not kitten (collectively known as Non Kitten
Items or NKIs). Robot must touch items to determine if they are kitten
or not. The game ends when robot finds kitten.
.P
You can move robot with the arrow keys, the EMACS keys (^N, ^P, ^B and 
^F for down, up, left and right), the keypad keys (all 8 directions), 
and the nethack keys (all 8 directions; hjklyubn is left, down, up, 
right, up-left, up-right, down-left and down-right).
.P
You can press Ctrl-L at any time to redraw the screen. You can press q 
or Esc at any time to quit.
.\"
.SH OPTIONS
You can optionally specify the number of Non Kitten Items to use. The 
default is 20.
.\"
.SH FILES
.BR robotfindskitten (6)
reads all of the files in the ~/.robotfindskitten and
SYSTEM_NKI_DIR (FIXME)
directories. Each line of each file becomes the description of a Non 
Kitten Item.
.\"
.SH ENVIRONMENT
.BR robotfindskitten (6)
uses the
.B HOME
environment variable to find the ~/.robotfindskitten directory.
.\"
.SH EXIT STATUS
The exit status is
.B 0
if robot found kitten;
.B 1
if you quit or there was a problem; and the signal number if
.BR robotfindskitten (6)
exits gracefully due to a signal.
.\"
.SH BUGS
When robot finds kitten, a congradulatory message is displayed right 
before the program exits. This message is only visible if your terminal 
doesn\'t have the smcup/rmcup capabilities. If you really want to see 
it, try entering:
.RS
.P
TERM=vt100 robotfindskitten
.RE
.\"
.SH AUTHOR
Written by Alexey Toptygin <alexeyt@freeshell.org> based on sources by 
Leonard Richardson and others.
