# SPDX-PackageName: robotfindskitten
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://codeberg.org/robotfindskitten/robotfindskitten
# SPDX-FileComment: Woodpecker CI ci workflow
# SPDX-FileCopyrightText: © 2026 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: GPL-2.0-or-later
---
when:
  - event: ["push", "pull_request", "manual"]
labels:
  platform: "linux/amd64"
steps:
  - name: "Robot Finds CI"
    image: "debian"
    commands: |
      # Dependency packages
      apt-get update
      apt-get -y install build-essential gnulib libncurses-dev texinfo texlive-latex-recommended pandoc

      # Build
      autoreconf -ifv
      ./configure
      make

      # Test
      make check
      make distcheck
