# SPDX-PackageName: robotfindskitten
# SPDX-PackageDownloadLocation: https://codeberg.org/robotfindskitten/robotfindskitten
# SPDX-FileCopyrightText: © 1997 Leonard Richardson and contributors
# SPDX-License-Identifier: GPL-2.0-or-later

nkidir = $(datadir)/games/robotfindskitten
nki_DATA = vanilla.nki
EXTRA_DIST = $(nki_DATA)
